/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTasksRouteImport } from './routes/_authed.tasks'
import { Route as AuthedSpidersRouteImport } from './routes/_authed.spiders'
import { Route as AuthedSchedulesRouteImport } from './routes/_authed.schedules'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedTasksIdRouteImport } from './routes/_authed.tasks.$id'
import { Route as AuthedSpidersIdRouteImport } from './routes/_authed.spiders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSpidersRoute = AuthedSpidersRouteImport.update({
  id: '/spiders',
  path: '/spiders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesRoute = AuthedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksIdRoute = AuthedTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedTasksRoute,
} as any)
const AuthedSpidersIdRoute = AuthedSpidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedSpidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/spiders': typeof AuthedSpidersRouteWithChildren
  '/tasks': typeof AuthedTasksRouteWithChildren
  '/spiders/$id': typeof AuthedSpidersIdRoute
  '/tasks/$id': typeof AuthedTasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/spiders': typeof AuthedSpidersRouteWithChildren
  '/tasks': typeof AuthedTasksRouteWithChildren
  '/spiders/$id': typeof AuthedSpidersIdRoute
  '/tasks/$id': typeof AuthedTasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/schedules': typeof AuthedSchedulesRoute
  '/_authed/spiders': typeof AuthedSpidersRouteWithChildren
  '/_authed/tasks': typeof AuthedTasksRouteWithChildren
  '/_authed/spiders/$id': typeof AuthedSpidersIdRoute
  '/_authed/tasks/$id': typeof AuthedTasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/schedules'
    | '/spiders'
    | '/tasks'
    | '/spiders/$id'
    | '/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/schedules'
    | '/spiders'
    | '/tasks'
    | '/spiders/$id'
    | '/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/schedules'
    | '/_authed/spiders'
    | '/_authed/tasks'
    | '/_authed/spiders/$id'
    | '/_authed/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/spiders': {
      id: '/_authed/spiders'
      path: '/spiders'
      fullPath: '/spiders'
      preLoaderRoute: typeof AuthedSpidersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules': {
      id: '/_authed/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthedSchedulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$id': {
      id: '/_authed/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthedTasksIdRouteImport
      parentRoute: typeof AuthedTasksRoute
    }
    '/_authed/spiders/$id': {
      id: '/_authed/spiders/$id'
      path: '/$id'
      fullPath: '/spiders/$id'
      preLoaderRoute: typeof AuthedSpidersIdRouteImport
      parentRoute: typeof AuthedSpidersRoute
    }
  }
}

interface AuthedSpidersRouteChildren {
  AuthedSpidersIdRoute: typeof AuthedSpidersIdRoute
}

const AuthedSpidersRouteChildren: AuthedSpidersRouteChildren = {
  AuthedSpidersIdRoute: AuthedSpidersIdRoute,
}

const AuthedSpidersRouteWithChildren = AuthedSpidersRoute._addFileChildren(
  AuthedSpidersRouteChildren,
)

interface AuthedTasksRouteChildren {
  AuthedTasksIdRoute: typeof AuthedTasksIdRoute
}

const AuthedTasksRouteChildren: AuthedTasksRouteChildren = {
  AuthedTasksIdRoute: AuthedTasksIdRoute,
}

const AuthedTasksRouteWithChildren = AuthedTasksRoute._addFileChildren(
  AuthedTasksRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSchedulesRoute: typeof AuthedSchedulesRoute
  AuthedSpidersRoute: typeof AuthedSpidersRouteWithChildren
  AuthedTasksRoute: typeof AuthedTasksRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSchedulesRoute: AuthedSchedulesRoute,
  AuthedSpidersRoute: AuthedSpidersRouteWithChildren,
  AuthedTasksRoute: AuthedTasksRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
